title: Because Windmills Can Be Giants
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.620142086641863
  brandStrength: 0.6236559
  lightness: 0.8098505965899676
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  rhythmicContrast: 0.2108132697176188
typography_spectrum: 0.937276
description: And we must fight them
navigation:
  - name: About this site…
    id: 091af1dd-21bd-456b-baf9-444b6acb26c4
    type: content
layout_spectrum: 0.6775831447448581
name: Windmill Fighter
